# Generated by Django 3.2.8 on 2021-11-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ic_no', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='IcNo')),
                ('name', models.CharField(editable=False, max_length=255, verbose_name='Name')),
                ('hp_no', models.CharField(max_length=15, verbose_name='Phone')),
            ],
        ),
    ]
