# Generated by Django 3.2.8 on 2021-11-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Victim', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resident',
            new_name='Victim',
        ),
    ]
