# Generated by Django 3.2.8 on 2021-12-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Victim', '0002_rename_resident_victim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='ic_no',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='IcNo'),
        ),
        migrations.AlterField(
            model_name='victim',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
